### ISSUE TITLE
missing notes

### ISSUE THREAD

**Issue by lauratomatis** [egenn/music#2]
Cb, Fb, E# and H# are not considered as notes

**Comment by egenn** [comment]
Hi, can you please elaborate? 
Is this a bug report or a feature request? What is the actual behavior and what is expected?
Thanks

**Comment by lauratomatis** [comment]
In the buildChord function this notes: Cb, Fb, E# and H# gives error

buildChord(root = "E#4", chord = "minor")
   E#4 minor chord
Error in if (all(nchar(notes) == 1)) notes <- toupper(notes) : 
  missing value where TRUE/FALSE needed

**Comment by egenn** [comment]
Thanks - that is the expected behavior, because the package uses 12-tone chromatic scale with the English naming convention (A-B-C-D-E-F-G).
Cb is B, Fb is E, E# is F. 
So, no notes are missing, but different systems use different names (https://en.wikipedia.org/wiki/Musical_note).
What notation are you using? German (C-D-E-F-G-A-H)?
